
import Head from "next/head";
import Navegation from "./Navegation";
import { useRouter } from "next/router";
const Layout = ({ children, namePage }) => {
    const location = useRouter();
    const { pathname } = location;
    let title = "";

    if (pathname === "/") {
        title = "Holaaaa! soy Héctor";
    } else if (pathname === "/hobbies") {
        title = "¿Cuales son mis hobbies?";
    } else if (pathname === "/experience") {
        title = "Mi experiencia!!";
    }
    return (
        <div className={style.area}>
            <Head>
                <title>HéctorZapata-{namePage}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navegation />
            <main className={style.main}>
                {children}
            </main>
        </div>
    )
}

//Style

import style from "../styles/Layout.module.css";

export default Layout
